# File: .github/workflows/pipeline.yaml
name: 'Feature to Develop'

on:
  push:
    branches: [feature/*]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Novo passo para verificar a variável
      - name: Check github.ref_name
        run: echo "github.ref_name is ${{ github.ref_name }}"

      - name: Copia os arquivos do repo
        uses: actions/checkout@v3

      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest Tests
        run: |
          pytest --rootdir=. \
            --cov=. \
            --cov-report=term \
            -v \
            -q

  create-pull-request:
    runs-on: ubuntu-latest
    needs: test # Este job só roda se o job 'test' passar

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessário para a action de PR

      - name: Check differences before PR action
        run: |
          git fetch origin develop:develop
          git fetch origin ${{ github.ref_name }}:${{ github.ref_name }}
          echo "Commits in ${{ github.ref_name }} not in develop:"
          git log develop..${{ github.ref_name }} --oneline
          echo "Count of commits in ${{ github.ref_name }} not in develop:"
          git rev-list --right-only --count develop...${{ github.ref_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: Create PR from feature branch'
          title: 'feat: PR from ${{ github.ref_name }}'
          body: |
            Este Pull Request foi criado automaticamente pelo GitHub Actions.

            Merge da branch `${{ github.ref_name }}` para `develop`.
          branch: ${{ github.ref_name }} # Branch de origem
          base: develop # Branch de destino
