name: 'Feature to Develop'

on:
  push:
    branches:
      - 'feature/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v3

      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest Tests
        run: |
          pytest --rootdir=. \
            --cov=. \
            --cov-report=term \
            -v \
            -q