name: 'Feature to Develop'

on:
  push:
    branches: [feature/*]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v3

      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest Tests
        run: |
          pytest --rootdir=. \
            --cov=. \
            --cov-report=term \
            -v \
            -q

  create-pull-request:
    runs-on: ubuntu-latest
    needs: test # Este job só roda se o job 'test' passar

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessário para a action de PR

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: Create PR from feature branch'
          title: 'feat: PR from ${{ github.ref_name }}'
          body: |
            Este Pull Request foi criado automaticamente pelo GitHub Actions.

            Merge da branch `${{ github.ref_name }}` para `develop`.
          branch: develop # Branch de destino
          base: ${{ github.ref_name }} # Branch de origem (a branch feature/* que disparou o workflow)