name: 'Feature to Develop'

on:
  push:
    branches:
      - 'feature/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v3

      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cria alteração para forçar commit
        run: |
          echo "Executado em $(date)" >> .auto-pr-log.txt

      - name: Commit das alterações
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .auto-pr-log.txt
          git commit -m "chore: trigger automatic PR" || echo "Nenhuma alteração para commitar"

      - name: Criar Pull Request para develop
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: 'Merge feature/${{ github.ref_name }} into develop'
          body: 'Automated PR from feature branch to develop'
