# File: .github/workflows/release-to-main.yaml
name: 'Release to Main'

on:
  push:
    branches: [release-*]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Novo passo para verificar a variável
      - name: Check github.ref_name
        run: echo "github.ref_name is ${{ github.ref_name }}"

      - name: Copia os arquivos do repo
        uses: actions/checkout@v3

      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest Tests
        run: |
          pytest --rootdir=. \
            --cov=. \
            --cov-report=term \
            -v \
            -q
      # Aqui você pode incluir os testes como no outro workflow

  create-pull-request:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check differences before PR
        run: |
          git fetch origin main
          git fetch origin ${{ github.ref_name }}
          echo "Commits in ${{ github.ref_name }} not in main:"
          git log origin/main..origin/${{ github.ref_name }} --oneline
          echo "Count of commits in ${{ github.ref_name }} not in main:"
          git rev-list --right-only --count origin/main...origin/${{ github.ref_name }}

      # AQUI está o bloco que você pediu
      - name: Create Pull Request using GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head ${{ github.ref_name }} \
            --title "release: PR from ${{ github.ref_name }} to main" \
            --body "Este Pull Request foi criado automaticamente pelo GitHub Actions.\n\nMerge da branch `${{ github.ref_name }}` para \`main\`."
